"""Refactor

Revision ID: 0deef8f26f98
Revises: 8fb90e01eeef
Create Date: 2021-07-09 13:00:42.470184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0deef8f26f98'
down_revision = '8fb90e01eeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_categories_category_id_fkey', 'users_categories', type_='foreignkey')
    op.drop_constraint('users_categories_user_id_fkey', 'users_categories', type_='foreignkey')
    op.create_foreign_key(None, 'users_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'users_categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_categories', type_='foreignkey')
    op.drop_constraint(None, 'users_categories', type_='foreignkey')
    op.create_foreign_key('users_categories_user_id_fkey', 'users_categories', 'categories', ['user_id'], ['id'])
    op.create_foreign_key('users_categories_category_id_fkey', 'users_categories', 'users', ['category_id'], ['id'])
    # ### end Alembic commands ###
