"""002

Revision ID: 2fc2c5c56daf
Revises: c60f97119515
Create Date: 2021-08-27 00:22:04.648735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc2c5c56daf'
down_revision = 'c60f97119515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
