"""add url in order

Revision ID: 37504bc0a072
Revises: 0deef8f26f98
Create Date: 2021-07-09 18:23:24.174109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37504bc0a072'
down_revision = '0deef8f26f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'url')
    # ### end Alembic commands ###
