"""003

Revision ID: 692af3ead7d8
Revises: 2fc2c5c56daf
Create Date: 2021-08-27 00:27:08.631797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692af3ead7d8'
down_revision = '2fc2c5c56daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_categories_user_id_fkey', 'users_categories', type_='foreignkey')
    op.drop_constraint('users_categories_category_id_fkey', 'users_categories', type_='foreignkey')
    op.create_foreign_key(None, 'users_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'users_categories', 'users', ['user_id'], ['id'])
    op.drop_column('users_categories', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_categories', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_categories', type_='foreignkey')
    op.drop_constraint(None, 'users_categories', type_='foreignkey')
    op.create_foreign_key('users_categories_category_id_fkey', 'users_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('users_categories_user_id_fkey', 'users_categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
