"""001

Revision ID: c60f97119515
Revises: 37504bc0a072
Create Date: 2021-08-26 23:53:17.114209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60f97119515'
down_revision = '37504bc0a072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_categories', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('users_categories_user_id_fkey', 'users_categories', type_='foreignkey')
    op.drop_constraint('users_categories_category_id_fkey', 'users_categories', type_='foreignkey')
    op.create_foreign_key(None, 'users_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_categories', type_='foreignkey')
    op.drop_constraint(None, 'users_categories', type_='foreignkey')
    op.create_foreign_key('users_categories_category_id_fkey', 'users_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('users_categories_user_id_fkey', 'users_categories', 'users', ['user_id'], ['id'])
    op.drop_column('users_categories', 'id')
    # ### end Alembic commands ###
