"""platform

Revision ID: 12538a64d626
Revises: 684b76398bcd
Create Date: 2021-05-03 23:00:32.560980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12538a64d626'
down_revision = '684b76398bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filters', sa.Column('platform', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filters', 'platform')
    # ### end Alembic commands ###
