"""unique constraint in filters

Revision ID: 37c73c6a3a2c
Revises: c94d0140711b
Create Date: 2021-05-06 03:06:59.167201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c73c6a3a2c'
down_revision = 'c94d0140711b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('filters_slug_key', 'filters', type_='unique')
    op.create_unique_constraint(None, 'filters', ['slug', 'platform'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filters', type_='unique')
    op.create_unique_constraint('filters_slug_key', 'filters', ['slug'])
    # ### end Alembic commands ###
