"""silent_mode

Revision ID: 684b76398bcd
Revises: f60f22c87473
Create Date: 2021-05-03 17:42:31.875069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684b76398bcd'
down_revision = 'f60f22c87473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('silent_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'silent_mode')
    # ### end Alembic commands ###
