"""platform2

Revision ID: c94d0140711b
Revises: 12538a64d626
Create Date: 2021-05-04 00:26:22.859739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94d0140711b'
down_revision = '12538a64d626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_platform', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_platform')
    # ### end Alembic commands ###
